spring.application.name=transaction-api

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=transaction_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:database.sql
spring.sql.init.data-locations=classpath:inserts.sql